name: exptracker
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  fl_chart: ^0.70.0
  intl: ^0.20.1
  flutter_colorpicker: ^1.1.0
  firebase_core: ^3.9.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7

  expense_repository:
    path: packages/expense_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  